### ISSUE TITLE
fails to boot in server enviroment

### ISSUE THREAD

**Issue by TheRanker** [PydingAbsorber/VestigesOfThePresent#1]
Threadmain
[03.03 19:15:59] [Server] Suspected ModsNONE
[03.03 19:15:59] [Server] Stacktrace:
[03.03 19:15:59] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:1.{}
[03.03 19:15:59] [Server] -- MOD vp --
[03.03 19:15:59] [Server] Details:
[03.03 19:15:59] [Server] 	Mod File/mods/Vestiges of the Present 1.20.1 v1.1.0.jar
[03.03 19:15:59] [Server] 	Failure messageVestiges of Present (vp) has failed to load correctly
[03.03 19:15:59] [Server] 		java.lang.RuntimeExceptionAttempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[03.03 19:15:59] [Server] 	Mod Version1.0.1
[03.03 19:15:59] [Server] 	Mod Issue URLNOT PROVIDED
[03.03 19:15:59] [Server] 	Exception messagejava.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[03.03 19:15:59] [Server] Stacktrace:
[03.03 19:15:59] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:1.{}
[03.03 19:15:59] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[03.03 19:15:59] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[03.03 19:15:59] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[03.03 19:15:59] [Server] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
[03.03 19:15:59] [Server] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
[03.03 19:15:59] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
[03.03 19:15:59] [Server] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
[03.03 19:15:59] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
[03.03 19:15:59] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[03.03 19:15:59] [Server] 	at com.pyding.vp.VestigesOfPresent.<init>(VestigesOfPresent.java:52) ~[Vestiges%20of%20the%20Present%201.20.1%20v1.1.0.jar%23590!/:1.0.{re:classloading}
[03.03 19:15:59] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[03.03 19:15:59] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[03.03 19:15:59] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[03.03 19:15:59] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[03.03 19:15:59] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[03.03 19:15:59] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.20.jar%23607!/:?] {}
[03.03 19:15:59] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.20.jar%23606!/:?] {}
[03.03 19:15:59] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[03.03 19:15:59] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[03.03 19:15:59] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[03.03 19:15:59] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[03.03 19:15:59] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
[03.03 19:15:59] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
[03.03 19:15:59] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
[03.03 19:15:59] [Server] -- System Details --

**Comment by PydingAbsorber** [comment]
Is it on the latest version? I just fixed it yesterday in v1.1.1

**Comment by TheRanker** [comment]
[03.03 19:15:59] [Server] Mod File/mods/Vestiges of the Present 1.20.1 v1.1.0.jar

was the version.. never tested your fixed version.

**Comment by PydingAbsorber** [comment]
So I found other problems with server, like overlay not render properly, empty slots crushing, some challenges not working and other stuff AND fixed it all in new version 1.1.2. I hope everything will be alright with :). 
https://modrinth.com/mod/vestiges-of-the-present/version/imjA01rh

**Comment by TheRanker** [comment]
tested and working perfect in server ... sorry for delay but just getting around to adding your mod back in and testings
